import keyMirror from 'key-mirror';

export default keyMirror({
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,
  LOGIN_ACTION_END: null,
  LOGIN_REQUEST: null,
  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,
  ON_USERNAME_FIELD_CHANGE: null,
  ON_PASSWORD_FIELD_CHANGE: null,
  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_REQUEST_SUCCESS: null,
  SESSION_TOKEN_REQUEST_FAILURE: null,
  HIDE_LOGIN_LOADING: null,
  LOGIN_USER_NAME: null,

  MAP_LOCATION_CHANGE: null,
  CURRENT_LOCATION_CHANGE: null,
  SET_DOGGIE_BUFFER_DESTINATION: null,
  SEARCH_STATE_SHIFT: null,
  FIND_NEARBY_DOGGIES_REQUEST: null,

  PROFILE_INFO_MODIFY: null,
  PROFILE_ITEM_PRESSED: null,
  PROFILE_EDITING_RESET: null,
  PROFILE_ITEM_EDITED: null,
  INIT_PROFILE_WITH_USER: null,

  DOGGIE_STATE_HOME: null,
  DOGGIE_DESTINATION_UPDATE: null,
  UPDATE_DOGGIE_LOCATION: null,
  INIT_DOGGIE_WITH_USER: null,
});
